---
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
    driver_config:
# https://github.com/test-kitchen/kitchen-docker/issues/285
      provision_command: mkdir -p /run/sshd
  - name: ubuntu-16.04
#  - name: centos-7
#  - name: alpine-3.6

suites:
  - name: default
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
  - name: default-logger-json
    run_list:
    attributes:
    includes:
      - ubuntu-18.04
