---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
  - name: default-logger-json
    run_list:
    attributes:
