---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: true
  ansible_cfg_path: test/vagrant/ansible.cfg
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
## FIXME! nginx/uwsgi: 502 bad gateway
#  - name: centos-7
#    provisioner:
## FIXME!/workaround: virtualenv bug in 2.2: https://github.com/ansible/ansible-modules-core/issues/5470
#      ansible_version: 2.1.2.0
#  - name: centos-6
### Ansible 2.2+/cryptography: https://github.com/ansible/ansible/issues/276
#    provisioner:
#      ansible_version: 2.1.2.0

## "Failed to complete #create action: [Broken pipe] on default-alpine-34"
## do we have python2 in default image?
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-logger-json
    run_list:
    attributes:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
