---

- name: MHN Client | registration
  include: registration.yml honeypot=conpot
- set_fact:
    deploy: /root/.registration_done-conpot

- shell: "echo {{ server_url }} | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//'"
  register: HPF_HOST
  changed_when: False
- set_fact:
    HPF_PORT: 10000
- shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"identifier\"]'"
  register: HPF_IDENT
  changed_when: False
- shell: "python -c 'import json;obj=json.load(file(\"{{ deploy }}\"));print obj[\"secret\"]'"
  register: HPF_SECRET
  changed_when: False

- name: Ubuntu | Install conpot dependencies
  apt:
    name:
      - git
      - libsmi2ldbl
      - snmp-mibs-downloader
      - python-pip
      - python-dev
      - libxml2-dev
      - libxslt-dev
      - libmysqlclient-dev
      - zlib1g-dev
      - python-virtualenv
      - supervisor
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install conpot dependencies
  yum:
    name:
      - git
      - supervisor
      - python-pip
      - python-devel
      - python-virtualenv
      - libxml2-devel
      - libxslt-devel
      - mariadb-devel
      - zlib-devel
## FIXME! rpm not available
#      - libsmi2ldbl
#      - snmp-mibs-downloader
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Ensure distribute is present
  pip: name=distribute state=present

- name: Install conpot virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: /opt/conpot/env
  with_items:
    - setuptools
    - git+https://github.com/threatstream/hpfeeds.git#egg=hpfeeds-dev
    - git+https://github.com/glastopf/conpot.git#egg=conpot-dev
    - git+https://github.com/glastopf/modbus-tk.git#egg=modbus-tk==0.4

- template: src=conpot.cfg dest=/opt/conpot/conpot.cfg mode=0644

- name: set conpot supervisor config
  copy: "src=conpot.conf dest={{ supervisor_confdir }}/conpot.{{ supervisor_ext }} mode=0644"
  notify:
    - supervisor update
