---

- name: Ubuntu | Install hpfeeds-logger-arcsight dependencies
  apt:
    name:
      - git
      - python-pip
      - python-dev
      - libgeoip-dev
      - python-virtualenv
      - supervisor
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | Install hpfeeds-logger-arcsight dependencies
  yum:
    name:
      - git
      - python-pip
      - python-virtualenv
      - supervisor
      - GeoIP-devel
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- include: hpfeeds-logger.yml

- name: configure IDENT
  set_fact:
    IDENT: hpfeeds-logger-arcsight
- name: check if existing configuration
  stat: path="/root/.mhn_{{ IDENT }}"
  register: sstat
- name: create a secret
  shell: "python -c 'import uuid;print str(uuid.uuid4()).replace(\"-\",\"\")' | tee /root/.mhn_{{ IDENT }}"
  when: not sstat.stat.exists
  no_log: "{{ mhn_no_log }}"
- name: recover existing hpfeeds secret
  command: "cat /root/.mhn_{{ IDENT }}"
## OR
#- command: python /opt/hpfeeds/broker/get_secret.py {{ IDENT }}
  register: SECRET
  changed_when: false
  no_log: "{{ mhn_no_log }}"
- name: configure CHANNELS
  set_fact:
    CHANNELS: 'amun.events,dionaea.connections,dionaea.capture,glastopf.events,beeswarm.hive,kippo.sessions,cowrie.sessions,,conpot.events,snort.alerts,suricata.events,wordpot.events,shockpot.events,p0f.events,elastichoney.events'

- name: enable hpfeeds json for arcsight
  template: src=arcsight.arcsight dest=/opt/hpfeeds-logger/arcsight.json mode=0600

- name: add hpfeeds broker user for json arcsight
  command: '/opt/hpfeeds/env/bin/python /opt/hpfeeds/broker/add_user.py "{{ IDENT }}" "{{ SECRET.stdout }}" "" "{{ CHANNELS }}"'

- name: configure hpfeeds-logger-arcsight in supervisor
  template: src=hpfeeds-logger-arcsight.conf dest=/etc/supervisor/conf.d/hpfeeds-logger-arcsight.conf mode=0644
  notify:
    - supervisor update
