---

## can't edit cron if password in expired state
- name: check state of user root
  command: "chage -l root"
  register: chage
  changed_when: false

- block:
    - name: "!!! setting random root password as current is expired !!!"
      shell: "openssl passwd -in /dev/urandom | head -1"
      register: pass
    - debug: msg="Root password was expired and has been changed to {{ pass.stdout }}"
  when: chage is defined and chage.sdtout.find('password must be changed') != -1
